baseURL = "https://praseedaconnects.com"
defaultContentLanguage = "en"
languageCode = "eb-gb"
title = "Praseeda connects"
theme = "dream"

enableGitInfo = true
enableRobotsTXT = true

#hasCJKLanguage = true

[services]
# tag = "tags"
# series = "series"

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

backgroundImage = "/img/lightmode.png"
backgroundImageDark = "/img/lightmode.png"

# images = ["img/rmc.png"]

author = "Praseeda"
description = "Praseeda's journey in tech and arts"
avatar = "/img/avatarnew.png"
avatarLink = "/about/me/"
headerTitle = "Praseeda connects"
motto = "Passions drive people"

footerBottomText = "Your smile looks wonderful, See you again!"
socialMediaLinks = ["https://www.linkedin.com/in/praseeda-achuthawarrier-a9a18127/", "https://instagram.com/praseedaaw"]

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

# email = "praseedaaw@gmail.com"

siteStartYear = 2025

favicon = "/img/favicon1.png"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
stickyNav = true
reorderNavItems = ["about", "posts", "search", "categories", "tags", "github"]
# collapseNavItems = ["posts", "categories", "tags", "rss"]
# noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
reorderShares = ["linkedin", "instagram", "whatsapp"]

[params.shareLinks]
linkedin = { name = "LinkedIn", url = "https://www.linkedin.com/in/praseeda-achuthawarrier-a9a18127/" }
instagram = { name = "Praseeda", url = "https://instagram.com/praseedaaw" }
whatsapp = { name = "WhatsApp", url = "https://wa.me/?text=" }

# Social media links
[params.social]
linkedin = { name = "Praseeda", url = "https://www.linkedin.com/in/praseeda-achuthawarrier-a9a18127/" }
instagram = { name = "Praseeda", url = "https://instagram.com/praseedaaw" }
whatsapp = { name = "WhatsApp", url = "https://wa.me/" }

[params.navItems]
about = { href = "content/about/me/", title = "About" }
github = { href = "https://github.com/praseedaaw", target = "_blank", icon = "logo-github", title = "GitHub" }
# posts = { href = "/posts/", title = "Posts" }

    
[params.advanced]
customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy-MM-dd"

[caches]
  [caches.images]
    dir = ':cacheDir/images'